# .github/workflows/test_datadog_metric.yml
name: Test Datadog Metric

on:
  push:

jobs:
  test-datadog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install requests

    - name: Run Test Metric Script
      env:
        DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      run: |
        python .github/scripts/test_datadog_metric.py
