# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Capture Logs
      id: capture_logs
      run: |
        echo "Capturing workflow logs..."
        # Redirect all output to workflow.log
        exec > >(tee -a workflow.log) 2>&1

    - name: Run tests
      id: test
      run: |
        pytest

    - name: Collect Workflow Logs
      if: always()
      run: |
        echo "Collecting workflow logs..."
        # Encode the logs to Base64
        LOGS=$(cat workflow.log | base64)
        # Set the output using the new GitHub Actions syntax
        echo "workflow_logs=$LOGS" >> $GITHUB_OUTPUT
      id: collect_logs

    - name: Send Datadog Metrics on Success
      if: success()
      env:
        DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        WORKFLOW_STATUS: success
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_RUN_URL: ${{ github.run_url }}
        DATADOG_REGION: us # Change to 'eu' if applicable
      run: |
        python .github/scripts/send_datadog_metrics.py

    - name: Send Datadog Metrics on Failure
      if: failure()
      env:
        DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        GITHUB_WORKFLOW: ${{ github.workflow }}
        WORKFLOW_STATUS: failure
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_RUN_URL: ${{ github.run_url }}
        DATADOG_REGION: us # Change to 'eu' if applicable
      run: |
        python .github/scripts/send_datadog_metrics.py

    - name: Send Workflow Logs to Datadog
      if: always()
      env:
        DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
        DATADOG_REGION: us # Change to 'eu' if applicable
        GITHUB_WORKFLOW: ${{ github.workflow }}
        WORKFLOW_STATUS: ${{ job.status }}
        GITHUB_RUN_ID: ${{ github.run_id }}
        GITHUB_RUN_URL: ${{ github.run_url }}
        GITHUB_ACTIONS_LOGS: ${{ steps.collect_logs.outputs.workflow_logs }}
      run: |
        python .github/scripts/send_datadog_scripts.py
